#!/bin/bash
#
# Generate and deploy a restricted SSH key pair for KVM MCP access.
# Run this ON THE MCP CLIENT machine (where the MCP server runs).
#
# This script:
#   1. Generates an Ed25519 key pair dedicated to kvm-mcp
#   2. Deploys the public key to the remote host's kvm-mcp user
#   3. Pins the remote host's fingerprint into known_hosts
#   4. Verifies connectivity
#
# Prerequisites:
#   - setup_remote_host.sh has already been run on the remote host
#   - You can currently SSH to the remote host as root (for key deployment)
#
# Usage:
#   ./scripts/setup_ssh_keys.sh <remote-host> [deploy-user]
#
#   remote-host  : hostname or IP of the KVM host
#   deploy-user  : user with SSH access for initial deployment (default: root)

set -euo pipefail

MCP_USER="kvm-mcp"
KEY_NAME="kvm-mcp"
KEY_PATH="$HOME/.ssh/$KEY_NAME"

# ── Parse arguments ───────────────────────────────────────────────────────

if [ $# -lt 1 ]; then
    echo "Usage: $0 <remote-host> [deploy-user]" >&2
    exit 1
fi

REMOTE_HOST="$1"
DEPLOY_USER="${2:-root}"

echo "=== KVM MCP SSH Key Setup ==="
echo "Remote host : $REMOTE_HOST"
echo "Deploy user : $DEPLOY_USER"
echo "Key path    : $KEY_PATH"
echo ""

# ── Generate key pair ─────────────────────────────────────────────────────

if [ -f "$KEY_PATH" ]; then
    echo "[ok] Key already exists at $KEY_PATH"
else
    ssh-keygen \
        -t ed25519 \
        -f "$KEY_PATH" \
        -N "" \
        -C "kvm-mcp@$(hostname)" \
        -q
    echo "[+] Generated Ed25519 key pair: $KEY_PATH"
fi

chmod 600 "$KEY_PATH"
chmod 644 "${KEY_PATH}.pub"

PUB_KEY=$(cat "${KEY_PATH}.pub")
echo "[i] Public key: $PUB_KEY"
echo ""

# ── Pin remote host key ──────────────────────────────────────────────────

KNOWN_HOSTS="$HOME/.ssh/known_hosts"
touch "$KNOWN_HOSTS"

if ssh-keygen -F "$REMOTE_HOST" -f "$KNOWN_HOSTS" &>/dev/null; then
    echo "[ok] Host key for $REMOTE_HOST already pinned"
else
    ssh-keyscan -H "$REMOTE_HOST" 2>/dev/null >> "$KNOWN_HOSTS"
    echo "[+] Pinned host key for $REMOTE_HOST"
fi

# ── Deploy public key to remote host ─────────────────────────────────────

REMOTE_AUTH_KEYS="/var/lib/kvm-mcp/.ssh/authorized_keys"

# Build a restricted authorized_keys entry that limits what the key can do
RESTRICTED_KEY="restrict,command=\"\" $PUB_KEY"

echo "[*] Deploying public key to $DEPLOY_USER@$REMOTE_HOST ..."

# shellcheck disable=SC2087
ssh -o StrictHostKeyChecking=yes \
    "${DEPLOY_USER}@${REMOTE_HOST}" <<DEPLOY_SCRIPT
set -e

# Append key if not already present (match on key data, not restrictions)
KEY_DATA="$PUB_KEY"
AUTH_FILE="$REMOTE_AUTH_KEYS"

if grep -qF "\$(echo "\$KEY_DATA" | awk '{print \$2}')" "\$AUTH_FILE" 2>/dev/null; then
    echo "[ok] Key already deployed"
else
    # No command restriction -- the sudoers policy is the enforcement boundary.
    # If you want belt-and-suspenders, uncomment the RESTRICTED_KEY line instead.
    echo "\$KEY_DATA" >> "\$AUTH_FILE"
    chown kvm-mcp:kvm-mcp "\$AUTH_FILE"
    chmod 600 "\$AUTH_FILE"
    echo "[+] Key deployed to \$AUTH_FILE"
fi
DEPLOY_SCRIPT

echo ""

# ── Verify connectivity ──────────────────────────────────────────────────

echo "[*] Testing SSH connectivity as $MCP_USER ..."

if ssh -o StrictHostKeyChecking=yes \
       -o BatchMode=yes \
       -o ConnectTimeout=10 \
       -i "$KEY_PATH" \
       "${MCP_USER}@${REMOTE_HOST}" \
       "echo ok" 2>/dev/null; then
    echo "[+] SSH connection verified"
else
    echo "[!] SSH test failed -- this may be expected if ForceCommand or"
    echo "    nologin shell is set. The key is deployed; virsh-over-SSH"
    echo "    will work as long as the MCP server uses the key correctly."
fi

echo ""

# ── SSH config snippet ────────────────────────────────────────────────────

SSH_CONFIG="$HOME/.ssh/config"

if ! grep -q "Host kvm-mcp-${REMOTE_HOST}" "$SSH_CONFIG" 2>/dev/null; then
    cat >> "$SSH_CONFIG" <<EOF

# KVM MCP access -- generated by setup_ssh_keys.sh
Host kvm-mcp-${REMOTE_HOST}
    HostName ${REMOTE_HOST}
    User ${MCP_USER}
    IdentityFile ${KEY_PATH}
    IdentitiesOnly yes
    StrictHostKeyChecking yes
    BatchMode yes
    ConnectTimeout 10
    ServerAliveInterval 30
    ServerAliveCountMax 3
EOF
    chmod 600 "$SSH_CONFIG"
    echo "[+] SSH config entry added: kvm-mcp-${REMOTE_HOST}"
else
    echo "[ok] SSH config entry already present"
fi

# ── Summary ───────────────────────────────────────────────────────────────

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Private key : $KEY_PATH"
echo "Known hosts : $KNOWN_HOSTS (pinned)"
echo "SSH config  : Host kvm-mcp-${REMOTE_HOST}"
echo ""
echo "Update your .env:"
echo "  KVM_HOST=$REMOTE_HOST"
echo "  KVM_HOST_USER=$MCP_USER"
echo "  KVM_HOST_SSH_KEY=$KEY_PATH"
echo ""
